[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from TestName
[ RUN      ] TestName.Subtest_1
[       OK ] TestName.Subtest_1 (0 ms)
[----------] 1 test from TestName (0 ms total)

[----------] 1 test from Test_Eyes_send_data_to_V1_func
[ RUN      ] Test_Eyes_send_data_to_V1_func.Subtest_2
Constructor Area_V1::Area_V1 is called
memory_in_V1: 0
Destructor Area_V1::~Area_V1 is called
[       OK ] Test_Eyes_send_data_to_V1_func.Subtest_2 (0 ms)
[----------] 1 test from Test_Eyes_send_data_to_V1_func (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (0 ms total)
[  PASSED  ] 2 tests.
